### ISSUE TITLE
Certificate issues and unavailability of the service

### ISSUE THREAD

**Issue by durack1** [ES-DOC/esdoc-errata-ws#12]
Hi folks, I went to browse https://errata.es-doc.org today and hit the issue screenshot below
![Screen Shot 2021-01-27 at 2 57 49 PM](https://user-images.githubusercontent.com/3229632/106065662-7518c400-60b0-11eb-90b3-1c27c2d11644.png)

It seems to be a certificate issue
![Screen Shot 2021-01-27 at 3 01 33 PM](https://user-images.githubusercontent.com/3229632/106065773-9bd6fa80-60b0-11eb-9f26-bae0e9642336.png)

**Comment by AtefBN** [comment]
Hello Paul, the esdoc services are experiencing few issues atm due to DNS re-mapping imposed by the service provider. 
We have takent the necessary steps, we should be back online any moment now. If the issue persists we will take further action.

**Comment by durack1** [comment]
@AtefBN thanks for the update, let me know when you think problems are sorted out and I'll take a test this side of the Atlantic across browsers

**Comment by AtefBN** [comment]
@durack1 We're back up with the errata services, everything has been sorted out. If you do encounter further issues please do ping me.

**Comment by durack1** [comment]
@AtefBN looks like I'm alive again on this side, just checked in firefox, so will close
